### ISSUE TITLE
Bump version for resque_extra_env

### ISSUE THREAD

**Issue by hector** [sshingler/capistrano-resque#110]
Hi,

For the moment, adding `gem 'capistrano-resque', '~> 0.2.2', require: false` to the Gemfile downloads a version without the resque_extra_env parameter.
Could you bump the gem version so we can have it?
Thanks :)

**Comment by martnst** [comment]
+1

**Comment by dmarkow** [comment]
Just pushed v0.2.3.

**Comment by martnst** [comment]
thx
