### ISSUE TITLE
Gem requires rake task

### ISSUE THREAD

**Issue by ulitiy** [sshingler/capistrano-resque#93]
I don't see any rake tasks provided by resque gem. So cap resque doesn't work at all.

**Comment by dmarkow** [comment]
Per Resque 1.x's README, I updated our own README to clarify that you need to `require 'resque/tasks'`.

Regarding the `bin/resque` stuff, that's only in the master/2.0 branch which we don't support yet, so I'm not going to update until Resque 2.0 drops (if ever).
